### ISSUE TITLE
running on windows  error

### ISSUE THREAD

**Issue by assiomatica** [kiskadigitalmedia/Enduro#8]
I am trying enduro on windows server 2012 but I got this error:

```
[09:54:40 |    +10.4] developer start
Juicebox is not set up
Unhandled rejection TypeError: Cannot read property '1' of null
    at Array.slice.call.map (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\flat_utilities\enduro_h
elpers.js:52:110)
    at Array.map (native)
    at enduro_helpers.ensure_directory_existence (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\fl
at_utilities\enduro_helpers.js:52:53)
    at babel.get_cultures.then (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\pregenerator\pregene
rator.js:70:27)
    at tryCatcher (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\release\util.
js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bl
uebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\r
elease\promise.js:567:18)
    at Promise._settlePromiseCtx (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\j
s\release\promise.js:604:10)
    at Async._drainQueue (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\releas
e\async.js:143:12)
    at Async._drainQueues (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird\js\relea
se\async.js:148:10)
    at Immediate.Async.drainQueues (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\node_modules\bluebird
\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\flat_utilities\enduro_helpers.js:52
        file_paths = Array.prototype.slice.call(arguments).map((file_path) => { return file_path.match(/^(.*)\/.*$/)[1]
})
                                                                                                                    ^

TypeError: Cannot read property '1' of null
    at Array.slice.call.map (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\flat_utilities\enduro_h
elpers.js:52:110)
    at Array.map (native)
    at enduro_helpers.ensure_directory_existence (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\fl
at_utilities\enduro_helpers.js:52:53)
    at read (C:\Users\adm-213100168\AppData\Roaming\npm\node_modules\enduro\libs\pregenerator\pregenerator.js:51:19)
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
```
what is wrong?

Thanks

**Comment by Gottwik** [comment]
Thanks for the report. Let me investigate.

**Comment by Gottwik** [comment]
Hey @assiomatica , which version of node.js are you running? You can find out by running `node -v`

**Comment by assiomatica** [comment]
Hi,

thanks for answer
v7.1.0

first was older , and I have updated to the last but nothing change, I got the error the same.

BTW Nice work , congratulation, I really like it! I have tested on osx and works perfectly.

A.

**Comment by Gottwik** [comment]
Wow, thank you.

Just update enduro (npm i enduro -g) and it should work smoothly. Issue was with the path delimiter.

**Comment by Gottwik** [comment]
btw, @assiomatica could you confirm this was solved?

**Comment by assiomatica** [comment]
Thanks but seems the patch is not available on npm

I have removed and reinstalled enduro but the error is still there.

may be I have to install a branch?

Thanks

Antonio

**Comment by assiomatica** [comment]
Hi

I have installed it from git directly

npm install git+https://github.com/kiskadigitalmedia/Enduro.git -g

now is working well

thank you for support.

Antonio

**Comment by Gottwik** [comment]
You are the best, thank you. Feel free to post more stuff if you find something.
